apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prj-isg-omcom-dv-cassandra-appset
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: prj-isg-omcom-dv-lua-services
        path: manifests/cassandra/charts/lua-services
        environment: dv
      - name: prj-isg-omcom-dv-scala-services
        path: manifests/cassandra/charts/scala-services
        environment: dv
  template:
    metadata:
      name: '{{name}}'
      namespace: argocd
      finalizers:
      - resources-finalizer.argocd.argoproj.io
    spec:
      project: prj-isg-omcom-dv-childapps
      source:
        repoURL: https://github.com/mengru-lotusflare/atlas-isg-omcom.git
        path: '{{path}}'
        targetRevision: main
        helm:
          valueFiles:
          - values.yaml
          - '{{cluster.metadata.labels.environment}}-values.yaml'
      destination:
        server: https://7A97A019883D103B23196EB489085B5D.gr7.ap-southeast-1.eks.amazonaws.com
        namespace: com-cassandra
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        retry:
          limit: 3
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 1m
